[package]
name = "docs-preprocessor"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[dependencies]
anyhow.workspace = true
clap.workspace = true
collections.workspace = true
gpui.workspace = true
mdbook = "0.4.40"
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
settings.workspace = true
regex.workspace = true
util.workspace = true

[lints]
workspace = true

[lib]
path = "src/docs_preprocessor.rs"

[[bin]]
name = "docs-preprocessor"
path = "src/main.rs"
