[package]
name = "docs-preprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mdbook = "0.4.40"
semver.workspace = true
serde.workspace = true
serde_json = "1.0.125"

[lints]
workspace = true

[[bin]]
name = "docs-preprocessor"
path = "src/main.rs"
